### ISSUE TITLE
`Union[None, str]` should not become `Optional[Union[None, str]]`

### ISSUE THREAD

**Issue by kbaikov** [Luttik/auto-optional#6]
Union[None, str] should not become Optional[Union[None, str]] 

This does not make sense.

auto-optional==0.1.11
python 3.9.7

**Comment by Luttik** [comment]
This is totally correct. I realized I forgot about this while they discussed this option in python bytes... If you have time to open a PR for this option you are welcome too, otherwise I'll do it myself when I have some time left.

**Comment by Luttik** [comment]
I've started a pull request with one test. I think this should (in addition to the others) cover most use-cases. I don't have time to start with the actual development today...

**Comment by Luttik** [comment]
Hi @kbaikov both the classic `Union[X, None]` as well as python 10's `X | None` are now supported due to #8

**Comment by Luttik** [comment]
🤦‍♂️ I realise I still need to update the docs and push to pypi. Give me a second.

**Comment by kbaikov** [comment]
@Luttik just tested and it looks fixed in auto-optional==0.2.0
Thank you!

**Comment by Luttik** [comment]
You're very welcome @kbaikov thanks for checking
